name: Deploy to Testflight

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install tools
        working-directory: example
        run: |
          flutter pub get
          cd ./ios && pod install
      - name: Setup SSH Keys and known_hosts for fastlane match
        env: 
          ACTIONS_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        run: |
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          chmod 700 "$SSH_PATH"
          echo "$ACTIONS_DEPLOY_KEY" > "$SSH_PATH/id_rsa"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
      - name: Deploy to TestFlight
        uses: maierj/fastlane-action@v1.4.0
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        with:
          lane: 'beta'
          subdirectory: 'example/ios'
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: ${{ secrets.DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS }}